### ISSUE TITLE
[BUG] Players can control multiple characters

### ISSUE THREAD

**Issue by AdamSai** [MakingGamesDreamTeam/MakingGamesExam-issues#3]
**Describe the bug**
When multiple animals are in the scene, some players control multiple characters

**To Reproduce**
1. Set a higher player number in the PlayersManager
2. Press play and move around

**Expected behavior**
Players should only control one character

**Comment by MrAbnox** [comment]
Press A to add player on Controller
Press Space to add player on keyboard

**Comment by MrAbnox** [comment]
Fixed with https://github.com/MakingGamesDreamTeam/MakingGamesExam/commit/2ec591c07ebad496cfe5e07dd5104ad67c3e3d5c
