### ISSUE TITLE
When players are holding blanket they can go through walls

### ISSUE THREAD

**Issue by MrAbnox** [MakingGamesDreamTeam/MakingGamesExam-issues#7]
**Describe the bug**
Once the player/s is/are holding the blanket they go through walls. 
Blanket also goes through walls
They also don't seem to have gravity applied to them once they are out of the room (This could be all the time tho? So needs to be tested)

**Comment by AdamSai** [comment]
Fixed wtih https://github.com/MakingGamesDreamTeam/MakingGamesExam/commit/52994ad77140b988b3b55c424dac465cfd626317

They still do not have any gravity, but we can make another issue if we ever get a level with verticality
