### ISSUE TITLE
Players stop moving when blanket is given to baby

### ISSUE THREAD

**Issue by MrAbnox** [MakingGamesDreamTeam/MakingGamesExam-issues#9]
**Describe the bug**
Players are unable to move when blanket is given to baby in the crib

This only happens to the players who where holding the blanket

**Comment by AdamSai** [comment]
Fixed with https://github.com/MakingGamesDreamTeam/MakingGamesExam/commit/4f5733d32f0e8bdb69c928033e07d3eb088b55de
